name: jdk-lint-build-push
env:
  DOCKERFILE_PATH: jdk/Dockerfile
  IMAGE_NAME: jdk
  IMAGE_VERSION: jdk-11-alpine

on:
  - pull_request
  - push

jobs:
  hadolint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Hadolint Action
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ${{env.DOCKERFILE_PATH}}
      - name: Build an image from Dockerfile
        run: |
          cd ${{env.IMAGE_NAME}}
          docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}}'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'